version: '3.1'

services:
  ad_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URI: postgres://testuser:supersecret@postgres:5432/testdb
      REDIS_URI: redis://redis:6379
      AUTO_MIGRATION: true
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
